# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-29 21:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_id', models.CharField(db_index=True, max_length=200)),
                ('company', models.CharField(choices=[('ofo', 'ofo'), ('mobike', 'mobike')], max_length=20)),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('gis_location', django.contrib.gis.db.models.fields.PointField(db_index=True, srid=4326)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
