# Generated by Django 3.2.16 on 2022-11-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='data',
            field=models.JSONField(),
        ),
    ]
