# Generated by Django 3.2.16 on 2023-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_alter_bike_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
