# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmultitoken', '0002_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='format',
            field=models.IntegerField(default=1, verbose_name='Key format'),
        ),
    ]
