# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-21 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authmultitoken', '0003_auto_20180821_1040'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='referer',
            unique_together=set([('token', 'value')]),
        ),
    ]
