# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 22:26
from __future__ import unicode_literals
import csn.models
import django.contrib.postgres.fields.jsonb
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('location_4d', csn.models.Point4DField(dim=4, geography=True, srid=4326)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LWApplication',
            fields=[
                ('destination_ptr', models.OneToOneField(db_constraint=False, auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='csn.Destination')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
                ('url', models.URLField()),
            ],
            bases=('csn.destination',),
        ),
        migrations.CreateModel(
            name='LWDevice',
            fields=[
                ('sensor_ptr', models.OneToOneField(db_constraint=False, auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='csn.Sensor', related_name='+')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('dev_class', models.CharField(choices=[('A', 'A'), ('C', 'C')], max_length=1)),
                ('counters_size', models.IntegerField(choices=[(2, 2), (4, 4)])),
                ('activation_type', models.CharField(choices=[('otaa', 'Over the Air Activation'), ('abp', 'Activation by personalisation')], max_length=5)),
                ('dev_addr', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(8)])),
                ('nwkskey', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(32)])),
                ('appskey', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(32)])),
                ('app_key', models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(32)])),
                ('dev_eui', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(16)])),
                ('user_id', models.IntegerField()),
                ('lw_application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lw_devices', to='csn.LWApplication')),
            ],
            bases=('csn.sensor',),
        ),
    ]
