# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:39
from __future__ import unicode_literals

import csn.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('csn', '0001_initial'), ('csn', '0002_auto_20170814_2114'), ('csn', '0003_auto_20170814_2130'), ('csn', '0004_lwapplication_destination_id'), ('csn', '0005_auto_20170830_0736')]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('location_4d', csn.models.Point4DField(dim=4, geography=True, srid=4326)),
                ('info', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'managed': False,
            },
        ),
    ]
