# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 21:14
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lwdevice',
            name='counters_size',
            field=models.IntegerField(choices=[(2, 2), (4, 4)], default=4),
        ),
        migrations.AlterField(
            model_name='lwdevice',
            name='dev_class',
            field=models.CharField(choices=[('A', 'A'), ('C', 'C')], default='A', max_length=1),
        ),
    ]
