# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 21:18
from __future__ import unicode_literals
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwdevice',
            name='dev_eui',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Should match the ^[0-9a-fA-F]+$ pattern'), django.core.validators.MinLengthValidator(16)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lwdevice',
            name='dev_addr',
            field=models.CharField(max_length=8, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Should match the ^[0-9a-fA-F]+$ pattern'), django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='lwdevice',
            name='nwkskey',
            field=models.CharField(max_length=32, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Should match the ^[0-9a-fA-F]+$ pattern'), django.core.validators.MinLengthValidator(32)]),
        ),
    ]
