# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 18:56
from __future__ import unicode_literals
from django.db import migrations


def update_website_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.filter(id=2).update(domain="smartcambridge.org", name="SmartCambridge")


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(update_website_name),
    ]
