# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-18 21:12
from __future__ import unicode_literals

import csn.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0001_squashed_0009_auto_20170708_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location_4d', csn.models.Point4DField(dim=4, geography=True, srid=4326)),
                ('device_type', models.CharField(choices=[('LWDevice', 'LoRaWAN Device')], max_length=16)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('device', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='csn.LWDevice', to_field='dev_eui')),
            ],
        ),
    ]
