# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 21:30
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0002_auto_20170814_2114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lwapplication',
            old_name='destination_id',
            new_name='tfcserver_destination_id',
        ),
        migrations.RenameField(
            model_name='lwdevice',
            old_name='sensor_id',
            new_name='tfcserver_sensor_id',
        ),
    ]
