# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 14:35
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0003_auto_20170805_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwdevice',
            name='app_key',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(32)]),
        ),
        migrations.AddField(
            model_name='lwdevice',
            name='appskey',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(32)]),
        ),
        migrations.AlterField(
            model_name='lwdevice',
            name='dev_addr',
            field=models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(8)]),
        ),
        migrations.AlterField(
            model_name='lwdevice',
            name='dev_eui',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(16)]),
        ),
        migrations.AlterField(
            model_name='lwdevice',
            name='lw_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lw_devices', to='csn.LWApplication'),
        ),
        migrations.AlterField(
            model_name='lwdevice',
            name='nwkskey',
            field=models.CharField(blank=True, max_length=32, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(32)]),
        ),
    ]
