# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0003_auto_20170814_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwapplication',
            name='destination_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
