# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-24 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0003_connection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensor',
            options={'managed': False},
        ),
    ]
