# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0003_lwapplication_lwcallbackurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwdevice',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lwdevice',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
