# Generated by Django 2.2.8 on 2019-12-08 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0004_auto_20190324_1947'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Destination',
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
