# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 07:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0004_lwapplication_destination_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lwapplication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lwdevice',
            name='lw_application',
        ),
        migrations.RemoveField(
            model_name='lwdevice',
            name='user',
        ),
        migrations.DeleteModel(
            name='LWApplication',
        ),
        migrations.DeleteModel(
            name='LWDevice',
        ),
    ]
