# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-20 18:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0004_auto_20170516_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='lwdevice',
            name='lw_application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='lw_devices', to='csn.LWApplication'),
            preserve_default=False,
        ),
    ]
