# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-06 17:44
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0005_lwdevice_activation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lwdevice',
            name='dev_eui',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-fA-F]+$', 'Needs to be hexadecimal'), django.core.validators.MinLengthValidator(16)]),
        ),
    ]
