# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-11 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0005_lwdevice_lw_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lwapplication',
            name='app_eui',
        ),
    ]
