# Generated by Django 3.2.16 on 2022-11-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0005_auto_20191208_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='info',
            field=models.JSONField(),
        ),
    ]
