# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 21:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0006_remove_lwapplication_app_eui'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lwcallbackurl',
            name='application',
        ),
        migrations.AddField(
            model_name='lwapplication',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LWCallbackURL',
        ),
    ]
