# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0006_auto_20170806_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destination',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='sensordata',
            options={'managed': False},
        ),
    ]
