# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-08 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csn', '0008_auto_20170708_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lwdevice',
            name='user',
        ),
        migrations.AddField(
            model_name='lwdevice',
            name='user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
