# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 21:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def smart_cambridge_user_migration(apps, schema_editor):
    SmartPanelUser = apps.get_model("smartpanel", "SmartPanelUser")
    SmartCambridgeUser = apps.get_model("smartcambridge", "SmartCambridgeUser")
    for smartpaneluser in SmartPanelUser.objects.all():
        smartcambridgeuser = SmartCambridgeUser()
        smartcambridgeuser.user = smartpaneluser.user
        smartcambridgeuser.accepted_tcs = smartpaneluser.accepted_tcs
        smartcambridgeuser.accepted_tcs_datetime = smartpaneluser.accepted_tcs_datetime
        smartcambridgeuser.account_type = smartpaneluser.account_type
        smartcambridgeuser.company_name = smartpaneluser.company_name
        smartcambridgeuser.company_email = smartpaneluser.company_email
        smartcambridgeuser.save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('smartpanel', '0010_smartpaneluser_accepted_tcs_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCambridgeUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                              related_name='smartcambridge_user', serialize=False,
                                              to=settings.AUTH_USER_MODEL)),
                ('accepted_tcs', models.BooleanField(default=False)),
                ('accepted_tcs_datetime', models.DateTimeField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')],
                                                  max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.RunPython(smart_cambridge_user_migration, migrations.RunPython.noop)
    ]
