# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 19:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_line_rendered_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='timetable',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
