# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 19:24
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('transport', '0015_vehiclejourney_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='bus_stop_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='cleardown_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='common_name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='stop',
            name='common_name_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='crossing',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='crossing_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='grand_parent_locality_name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='stop',
            name='grid_type',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='indicator',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='indicator_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='landmark',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='landmark_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='locality_name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='stop',
            name='modification',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='modification_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='notes_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='nptg_locality_code',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='stop',
            name='parent_locality_name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='stop',
            name='plate_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='revision_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='short_common_name',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='short_common_name_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='status',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='street',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='street_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='suburb',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='suburb_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='timing_status',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='town',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='stop',
            name='town_lang',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
