# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0016_auto_20170308_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='administrative_area_code',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='bearing',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='bus_stop_type',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='cleardown_code',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='common_name_lang',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='creation_datetime',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='crossing',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='crossing_lang',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='default_wait_time',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='easting',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='grand_parent_locality_name',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='grid_type',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='indicator_lang',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='landmark',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='landmark_lang',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='locality_centre',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='modification',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='modification_datetime',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='northing',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='notes_lang',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='nptg_locality_code',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='parent_locality_name',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='plate_code',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='revision_number',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='short_common_name',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='short_common_name_lang',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='status',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='stop_type',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='street',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='street_lang',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='suburb',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='suburb_lang',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='timing_status',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='town',
        ),
        migrations.RemoveField(
            model_name='stop',
            name='town_lang',
        ),
        migrations.AddField(
            model_name='stop',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
