# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0017_auto_20170309_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='stop_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='timetable',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
