# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 22:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0019_auto_20170331_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='stop_list',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
