# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-22 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0021_auto_20170401_2011'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_times',
                                           to='transport.Stop')),
            ],
        ),
        migrations.RemoveField(
            model_name='vehiclejourney',
            name='timetable',
        ),
        migrations.AddField(
            model_name='timetable',
            name='vehicle_journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journey_times',
                                    to='transport.VehicleJourney'),
        ),
    ]
