# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-22 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0022_auto_20171022_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
