# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-22 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0023_vehiclejourney_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='last_stop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetable',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
