# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0024_auto_20171022_1951'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['vehicle_journey', 'stop', 'time', 'order', 'last_stop'], name='transport_t_vehicle_d61fcc_idx'),
        ),
    ]
