# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 16:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0025_auto_20171109_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDaysOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', django.contrib.postgres.fields.ranges.DateRangeField()),
                ('vehicle_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_days_operation', to='transport.VehicleJourney')),
            ],
        ),
    ]
