# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0026_specialdaysoperation'),
    ]

    operations = [
        migrations.AddField(
            model_name='specialdaysoperation',
            name='operates',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
