# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0027_specialdaysoperation_operates'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='nonoperation_bank_holidays',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vehiclejourney',
            name='operation_bank_holidays',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='days_of_week',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
