# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0028_auto_20171118_2158'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='specialdaysoperation',
            index=models.Index(fields=['vehicle_journey', 'days', 'operates'], name='transport_s_vehicle_f47da5_idx'),
        ),
    ]
