# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-09 15:55
from __future__ import unicode_literals

from django.db import migrations, models


def delete_all_lines(apps, schema_editor):
    Line = apps.get_model('transport', 'Line')
    Line.objects.all().delete()
    Route = apps.get_model('transport', 'Route')
    Route.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0030_line_area'),
    ]

    operations = [
        migrations.RunPython(delete_all_lines),
    ]
