# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-13 19:40
from __future__ import unicode_literals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0032_auto_20180610_1935'),
    ]

    operations = [
        migrations.RunSQL("DROP INDEX transport_route_line_id_4f836707_like;"),
        migrations.RunSQL("ALTER TABLE transport_route ALTER COLUMN line_id TYPE int USING line_id::integer;"),
        migrations.RunSQL('CREATE INDEX "transport_route_line_id_4f836707" ON "transport_route" ("line_id");'),
    ]
