# Generated by Django 2.2.10 on 2020-10-22 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0033_fix_route_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclejourney',
            name='direction',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiclejourney',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='transport.Line'),
        ),
        migrations.AddField(
            model_name='vehiclejourney',
            name='tnds_zone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclejourney',
            name='journey_pattern',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to='transport.JourneyPattern'),
        ),
        migrations.CreateModel(
            name='TimetableStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('direction', models.CharField(blank=True, max_length=100, null=True)),
                ('run_time', models.DurationField()),
                ('wait_time', models.DurationField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('last_stop', models.BooleanField(default=False)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_stops', to='transport.Stop')),
                ('vehicle_journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_stops', to='transport.VehicleJourney')),
            ],
        ),
        migrations.AddIndex(
            model_name='timetablestop',
            index=models.Index(fields=['vehicle_journey', 'stop', 'time', 'order', 'last_stop'], name='transport_t_vehicle_8e5255_idx'),
        ),
    ]
