# Generated by Django 2.2.10 on 2020-10-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0035_auto_20201024_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(),
        ),
    ]
