# Generated by Django 2.2.10 on 2020-10-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0036_auto_20201024_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='standard_destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='standard_origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
