# Generated by Django 3.2.16 on 2023-02-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0038_auto_20221128_2131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journeypatterntiminglink',
            name='journey_pattern_section',
        ),
        migrations.RemoveField(
            model_name='journeypatterntiminglink',
            name='stop_from',
        ),
        migrations.RemoveField(
            model_name='journeypatterntiminglink',
            name='stop_to',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='vehicle_journey',
        ),
        migrations.AlterField(
            model_name='line',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specialdaysoperation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timetablestop',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='JourneyPattern',
        ),
        migrations.DeleteModel(
            name='JourneyPatternSection',
        ),
        migrations.DeleteModel(
            name='JourneyPatternTimingLink',
        ),
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
