# Generated by Django 3.2.16 on 2023-02-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0039_auto_20230216_1924'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.CharField(db_index=True, max_length=255)),
                ('line_name', models.CharField(max_length=255)),
                ('outbound_description', models.CharField(max_length=255)),
                ('inbound_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='line',
            old_name='line_id',
            new_name='service_code',
        ),
        migrations.RemoveField(
            model_name='line',
            name='area',
        ),
        migrations.RemoveField(
            model_name='line',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='line',
            name='line_name',
        ),
        migrations.AlterField(
            model_name='operator',
            name='short_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operator',
            name='trading_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
