# Generated by Django 3.2.16 on 2023-03-25 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0040_auto_20230226_1753'),
    ]

    operations = [

        migrations.CreateModel(
            name='TransXChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('creation_date_time', models.DateTimeField()),
                ('modification_date_time', models.DateTimeField()),
                ('schema_version', models.CharField(max_length=50)),
                ('revision_number', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SpecialDaysOperation',
        ),
        migrations.DeleteModel(
            name='LineLine',
        ),
        migrations.DeleteModel(
            name='VehicleJourney',
        ),
        migrations.DeleteModel(
            name='Stop',
        ),
        migrations.DeleteModel(
            name='Line',
        ),
        migrations.DeleteModel(
            name='Route',
        ),
        migrations.DeleteModel(
            name='Operator',
        ),
        migrations.DeleteModel(
            name='TimetableStop',
        ),
    ]
