# Generated by Django 3.2.16 on 2023-04-21 18:12

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0042_journeypattern_journeypatterntiminglink_line_operator_service_stop_vehiclejourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='journeypattern',
            name='coordinates',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326),
        ),
    ]
