# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfc_gis', '0002_area_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Area',
        ),
    ]
