# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-18 21:34
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartpanel', '0002_layout_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='layout',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='smartpanel.Layout'),
        ),
        migrations.AddField(
            model_name='screen',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
    ]
