# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-18 16:49
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('smartpanel', '0003_auto_20180218_2134'),
    ]

    operations = [
        migrations.RenameModel('Screen', 'Display'),
        migrations.AddField(
            model_name='display',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='layout',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING,
                                    to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
