# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-20 15:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('smartpanel', '0007_auto_20180609_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartPanelUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True,
                                              related_name='smartpanel_user', serialize=False,
                                              to=settings.AUTH_USER_MODEL)),
                ('accepted_tcs', models.BooleanField(default=False)),
            ],
        ),
    ]
