# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-29 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpanel', '0008_smartpaneluser'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartpaneluser',
            name='account_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('business', 'Business')], default='personal', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='smartpaneluser',
            name='company_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='smartpaneluser',
            name='company_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
