# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-01 19:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpanel', '0009_auto_20180729_1451'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartpaneluser',
            name='accepted_tcs_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
