# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-16 21:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartpanel', '0010_smartpaneluser_accepted_tcs_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartpaneluser',
            name='user',
        ),
        migrations.DeleteModel(
            name='SmartPanelUser',
        ),
    ]
