# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-01-17 18:17
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpanel', '0011_auto_20180816_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pocket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('params', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
