# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-01 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpanel', '0012_pocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='map_reload_limit',
            field=models.IntegerField(null=True),
        ),
    ]
