# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-10-04 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpanel', '0013_display_map_reload_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display',
            name='map_reload_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
