# Generated by Django 3.2.16 on 2022-11-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartpanel', '0014_auto_20191004_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='configuration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='layout',
            name='design',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='pocket',
            name='params',
            field=models.JSONField(),
        ),
    ]
