# docker-compose file for local development and testing with container image.
version: '3.2'
services:
  devserver: &devserver
    build:
      context: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    depends_on:
      - "db"
      - "debugsmtp"
    # For devserver, mount the local directory inside the container as a volume
    # to allow local changes to be reflected without having to re-build the
    # container.
    volumes:
      - type: bind
        source: ./
        target: /usr/src/app
        read_only: false
    environment:
      - PORT=8000
      - DJANGO_SETTINGS_MODULE=tfc_web.settings_dev
      - DJANGO_DB_ENGINE=django.contrib.gis.db.backends.postgis
      - DJANGO_DB_HOST=db
      - DJANGO_DB_NAME=tfcweb
      - DJANGO_DB_USER=tfcweb
      - DJANGO_DB_PASSWORD=tfcweb
      - DJANGO_EMAIL_HOST=debugsmtp
      - DJANGO_EMAIL_PORT=1025
  migrate:
    <<: *devserver
    entrypoint: ["wait-for-it", "db:5432", "-t", "5", "--"]
    command: ["./manage.py", "migrate"]
  makemigrations:
    <<: *devserver
    entrypoint: ["wait-for-it", "db:5432", "-t", "5", "--"]
    command: ["./manage.py", "makemigrations"]
  shell:
    <<: *devserver
    command: ["shell"]
  db:
    image: mdillon/postgis:10
    environment:
      - POSTGRES_DB=tfcweb
      - POSTGRES_USER=tfcweb
      - POSTGRES_PASSWORD=tfcweb
  debugsmtp:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
